### ISSUE TITLE
Support for premium account

### ISSUE THREAD

**Issue by rollecode** [deltaclock/emu-paradise-download#1]
First of all, I love your script! so easy to dl directly to my retroPC. Any way for it to support premium account (unlimited simultaneous downloads, faster speeds etc...). Now when I try to download more than 2, it just downloads a couple of kb file and doesn't inform anything (I guess it's just the limitation notification that comes up on the website).

Thoughts?

**Comment by deltaclock** [comment]
Glad you liked the script! Yes it shouldnt be too hard to implement the support for a premium account even though the script original logic wasnt that :D The reason u might not get be able to download 2 files at the same time might be the "happy hour" the site has, which is not enabled always.
Also threading is in my todo list for this script, but wasnt implemented since the max games u can download on the same time is 2.
The only problem that might come by supporting premium is that i dont have premium to test and check if everything works, since premium doesnt have the captcha check (that i bypass ) etc though ill try to add it as a beta option.
Lastly another problem that the website has is that the download links for some platfoms are inconsistent,so trickery required there as well but those platforms are not on high demand thus this is last priority.
Feel free to open a pull request if u wanna add something or fix something, and for any questions about the code you can open another issue :+1:

**Comment by deltaclock** [comment]
Closing this since emuparadise is officially closed. The script still works, but with max 2 downloads.
